### Get all blogs
GET http://localhost:3001/api/blogs


###Post new blog to db
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Postilla luotu blogi",
    "author": "JokuHermanni",
    "url": "http://www.google.fi",
    "likes": 50
}

###delete created blog
DELETE http://localhost:3001/api/blogs/5b4725fb9067542140a4ff66