GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/notes

###

POST http://localhost:3001/api/notes
content-type: application/json

{
  "content": "testikakku",
  "important": true,
  "userId": "5b4e475de559101f040b2515"
  }
}